insert into customer (first_name, last_name, email, gender, city) values ('Drud', 'Naisby', 'dnaisby0@goo.gl', 'Genderfluid', 'Starobachaty');
insert into customer (first_name, last_name, email, gender, city) values ('Darcy', 'Flahy', 'dflahy1@deviantart.com', 'Female', 'Suntar');
insert into customer (first_name, last_name, email, gender, city) values ('Claudian', 'Ricardo', 'cricardo2@tinyurl.com', 'Male', 'Santa Rita');
insert into customer (first_name, last_name, email, gender, city) values ('Farr', 'Kingsman', 'fkingsman3@nps.gov', 'Male', 'Wonosari');
insert into customer (first_name, last_name, email, gender, city) values ('Ermentrude', 'Roy', 'eroy4@histats.com', 'Female', 'Obong');
insert into customer (first_name, last_name, email, gender, city) values ('Sarine', 'Dalli', 'sdalli5@nsw.gov.au', 'Female', 'Dingjiaqiao');
insert into customer (first_name, last_name, email, gender, city) values ('Chick', 'Horstead', 'chorstead6@ifeng.com', 'Male', 'Valvedditturai');
insert into customer (first_name, last_name, email, gender, city) values ('Conni', 'Jerrom', 'cjerrom7@delicious.com', 'Female', 'Panaitólion');
insert into customer (first_name, last_name, email, gender, city) values ('Cymbre', 'Moynihan', 'cmoynihan8@nyu.edu', 'Female', 'Gobō');
insert into customer (first_name, last_name, email, gender, city) values ('Kara-lynn', 'Maskelyne', 'kmaskelyne9@t-online.de', 'Female', 'Słotowa');
insert into customer (first_name, last_name, email, gender, city) values ('Lanny', 'Parmeter', 'lparmetera@facebook.com', 'Female', 'Murmuiža');
insert into customer (first_name, last_name, email, gender, city) values ('Katha', 'Braunds', 'kbraundsb@freewebs.com', 'Polygender', 'Richard-Toll');
insert into customer (first_name, last_name, email, gender, city) values ('Gaston', 'Strodder', 'gstrodderc@ucla.edu', 'Male', 'Vinsady');
insert into customer (first_name, last_name, email, gender, city) values ('Marlyn', 'Osinin', 'mosinind@gnu.org', 'Female', 'Polešovice');
insert into customer (first_name, last_name, email, gender, city) values ('Phaedra', 'Ralfe', 'pralfee@tinyurl.com', 'Female', 'Henglan');
insert into customer (first_name, last_name, email, gender, city) values ('Leyla', 'Whitford', 'lwhitfordf@howstuffworks.com', 'Female', 'Jianshe');
insert into customer (first_name, last_name, email, gender, city) values ('Waylen', 'Lecount', 'wlecountg@dmoz.org', 'Male', 'Pak Phanang');
insert into customer (first_name, last_name, email, gender, city) values ('Kristen', 'Murdie', 'kmurdieh@plala.or.jp', 'Female', 'Pandakan');
insert into customer (first_name, last_name, email, gender, city) values ('Alberta', 'Lapley', 'alapleyi@wikispaces.com', 'Bigender', 'Caluire-et-Cuire');
insert into customer (first_name, last_name, email, gender, city) values ('Prentiss', 'Bynold', 'pbynoldj@sciencedirect.com', 'Male', 'Manouba');
insert into customer (first_name, last_name, email, gender, city) values ('Ernesta', 'Tierny', 'etiernyk@homestead.com', 'Female', 'Yajiang');
insert into customer (first_name, last_name, email, gender, city) values ('Doyle', 'Skocroft', 'dskocroftl@cafepress.com', 'Male', 'Uren’');
insert into customer (first_name, last_name, email, gender, city) values ('Joly', 'Ogdahl', 'jogdahlm@omniture.com', 'Female', 'Phalaborwa');
insert into customer (first_name, last_name, email, gender, city) values ('Mariellen', 'Hucknall', 'mhucknalln@chicagotribune.com', 'Female', 'Ihosy');
insert into customer (first_name, last_name, email, gender, city) values ('Britt', 'Robbins', 'brobbinso@npr.org', 'Female', 'Zaragoza');
insert into customer (first_name, last_name, email, gender, city) values ('Darrell', 'Palfrie', 'dpalfriep@google.ca', 'Male', 'Houping');
insert into customer (first_name, last_name, email, gender, city) values ('Kiel', 'Norres', 'knorresq@narod.ru', 'Male', 'Heby');
insert into customer (first_name, last_name, email, gender, city) values ('Querida', 'MacTerrelly', 'qmacterrellyr@salon.com', 'Genderfluid', 'Manjiang');
insert into customer (first_name, last_name, email, gender, city) values ('Dorothea', 'MacSween', 'dmacsweens@ucla.edu', 'Female', 'San Juan de los Morros');
insert into customer (first_name, last_name, email, gender, city) values ('Etta', 'Sheron', 'esheront@bloglines.com', 'Female', 'Liuyuan');
insert into customer (first_name, last_name, email, gender, city) values ('Corina', 'Snape', 'csnapeu@cam.ac.uk', 'Female', 'Akim Oda');
insert into customer (first_name, last_name, email, gender, city) values ('Marlowe', 'Yakuntsov', 'myakuntsovv@squidoo.com', 'Male', 'Ash Shafā');
insert into customer (first_name, last_name, email, gender, city) values ('Walsh', 'Dikles', 'wdiklesw@skype.com', 'Male', 'Zhantang');
insert into customer (first_name, last_name, email, gender, city) values ('Donni', 'Crone', 'dcronex@privacy.gov.au', 'Polygender', 'Lydenburg');
insert into customer (first_name, last_name, email, gender, city) values ('Muffin', 'Endean', 'mendeany@alibaba.com', 'Female', 'Telouet');
insert into customer (first_name, last_name, email, gender, city) values ('Reinhold', 'Sawtell', 'rsawtellz@netlog.com', 'Male', 'Urengoy');
insert into customer (first_name, last_name, email, gender, city) values ('Lani', 'Treneman', 'ltreneman10@com.com', 'Female', 'Gondang');
insert into customer (first_name, last_name, email, gender, city) values ('Alister', 'Mirfin', 'amirfin11@1und1.de', 'Male', 'Banjar Dukuh');
insert into customer (first_name, last_name, email, gender, city) values ('Nessie', 'Liggens', 'nliggens12@redcross.org', 'Female', 'Pangkalanbuun');
insert into customer (first_name, last_name, email, gender, city) values ('Jeana', 'Gunton', 'jgunton13@moonfruit.com', 'Female', 'Znamenka');
insert into customer (first_name, last_name, email, gender, city) values ('Bettye', 'Pitkaithly', 'bpitkaithly14@archive.org', 'Female', 'Guli');
insert into customer (first_name, last_name, email, gender, city) values ('Malinda', 'Vanlint', 'mvanlint15@opensource.org', 'Bigender', 'Chalaco');
insert into customer (first_name, last_name, email, gender, city) values ('Rocky', 'Camsey', 'rcamsey16@barnesandnoble.com', 'Male', 'Södra Sandby');
insert into customer (first_name, last_name, email, gender, city) values ('Allegra', 'Ambroisin', 'aambroisin17@jimdo.com', 'Female', 'Cotuí');
insert into customer (first_name, last_name, email, gender, city) values ('Mahala', 'Crosgrove', 'mcrosgrove18@clickbank.net', 'Female', 'Gradac');
insert into customer (first_name, last_name, email, gender, city) values ('Keri', 'Brennans', 'kbrennans19@php.net', 'Female', 'Freetown');
insert into customer (first_name, last_name, email, gender, city) values ('Marilyn', 'Huntingford', 'mhuntingford1a@unc.edu', 'Female', 'Oss');
insert into customer (first_name, last_name, email, gender, city) values ('Elvyn', 'Viveash', 'eviveash1b@123-reg.co.uk', 'Male', 'Saint-Jean-de-Luz');
insert into customer (first_name, last_name, email, gender, city) values ('Leticia', 'Woodward', 'lwoodward1c@sohu.com', 'Female', 'Algoz');
insert into customer (first_name, last_name, email, gender, city) values ('Angelika', 'Lattie', 'alattie1d@theguardian.com', 'Genderqueer', 'Dingcheng');
